export const GET_ERRORS = "GET_ERRORS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";

export const GET_ACCOUNT = "GET_ACCOUNT";
export const GET_ACCOUNTS = "GET_ACCOUNTS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
